### ISSUE TITLE
Wrong Servers on self hosted instance when installed

### ISSUE THREAD

**Issue by gianmarcotoso** [aeharding/voyager#124]
I have create a self-hosted instance with a simple docker-compose.yml file:

```
version: '3'

services:
    wefwef:
        image: ghcr.io/aeharding/wefwef:latest
        container_name: wefwef
        ports:
            - ${WEFWEF_PORT:-5314}:5314
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TZ:-Europe/Rome}
            - CUSTOM_LEMMY_SERVERS=${WEFWEF_SERVERS:-lemmy.world,feddit.it}
        restart: unless-stopped
```

The value of `CUSTOM_LEMMY_SERVERS` is read correctly when navigating to said instance with a browser (either desktop or mobile, Firefox or Chrome), but if I install the PWA the server list changes to what I assume is the default list (lemmy.world, lemmy.ml, beehaw.org, sh.itjust.works); the website to which the PWA points to is my own instance, and not another one.

**STEPS TO REPRODUCE**
1. Create a `docker-compose.yml` file with the above contents
2. Create an `.env` file in the same directory and fill in the values (optional, not creating the file uses the default values specified in the docker-compose.yml)
3. Create an nginx reverse proxy to a domain or subdomain that points to the server you're working on, restart nginx, create the certificates with certbot
4. Start the container with `docker-compose up -d`
5. Navigate to your instance, see correct server list
6. Install the PWA, see default (?) server list
